global.queue="QUEUE"
Function('j', 't',
global.j=`self=unescape("global.queue=%22QQQ%22%0aFunction('j', 't',%0aglobal.j=ttjjtt)(global.j, 'tt')")
    .replace(/tt/g, t)
    .replace(/jj/g, j)
    .replace('QQQ', 'queue'.toUpperCase())
o_N=unescape('%3f%6e')
o_Q=unescape('%3f%71')
o_C=unescape('%3f%63')
o_S=unescape('%3f%73')
o_T=unescape('%3f%74')
queue=(queue+':'+self.replace(new RegExp(unescape('%0a'), 'g'), o_N)
    .replace(/"/g, o_Q)
    .replace(/:/g, o_C)
    .replace(/ /g, o_S)
    .replace(new RegExp(unescape('%09'), 'g'), o_T))
arr=queue.split(":")
nextQuine=arr[0]
nextQueue=arr.slice(1).join(":")
console.log(nextQuine
    .replace(new RegExp(unescape('%5c')+o_N, 'g'), unescape('%0a'))
    .replace(new RegExp(unescape('%5c')+o_Q, 'g'), '"')
    .replace(new RegExp(unescape('%5c')+o_C, 'g'), ':')
    .replace(new RegExp(unescape('%5c')+o_S, 'g'), ' ')
    .replace(new RegExp(unescape('%5c')+o_T, 'g'), unescape('%09'))
    .replace('queue'.toUpperCase(), nextQueue))`)(global.j, '`')
